Automatically create the local data folder
ModelarData/ModelarDB-RS pull request #203
Opened 2024-08-15 18:54 UTC by skejserjensen

This PR will make `modelardbd` automatically create the local data folder if it does not exist instead of returning an error.

2024-08-15 19:07 UTC, CGodiksen requested changes

2024-08-15 19:07 UTC, CGodiksen commented on crates/modelardb_common/src/storage.rs
>      /// Create a new [`DeltaLake`] that manages the delta tables in `data_folder_path` if it exists.
Maybe update this doc comment now that it does not matter if it exists.

2024-08-15 19:07 UTC, CGodiksen commented on crates/modelardb_common/src/storage.rs
>      /// Returns a [`DeltaTableError`] if `data_folder_path` is not accessible.
Maybe change this to say that an error is returned if the path cannot be created if it does not already exist.  I am not sure `LocalFileSystem::new_with_prefix` can fail now that we create the path before.

2024-08-15 19:19 UTC, CGodiksen approved these changes

2024-08-16 05:53 UTC, chrthomsen approved these changes

2024-08-16 06:28 UTC, merged