Update dependencies
ModelarData/ModelarDB-RS pull request #51
Opened 2022-12-06 15:49 UTC by skejserjensen

This PR primarily updates Apache Arrow DataFusion to [v15.0.0](https://crates.io/crates/datafusion/15.0.0) and fixes all known breaking changes. New versions of Apache Arrow DataFusion usually have breaking changes, so updating to each new release ensures that the number of changes required does not accumulate. The changes in v15.0.0 generally only required minor fixes for the code and the tests. However, as `convert_simple_data_type()` has been changed from a public function in Apache Arrow DataFusion [v14.0.0](https://github.com/apache/arrow-datafusion/blob/14.0.0/datafusion/sql/src/planner.rs#L2812) to a private method in Apache Arrow DataFusion [v15.0.0](https://github.com/apache/arrow-datafusion/blob/15.0.0/datafusion/sql/src/planner.rs#L2790) without the addition of a new alternative API for translating types, the v14.0.0 version of `convert_simple_data_type()` and a private function it calls had to be copied to [parser.rs.](https://github.com/ModelarData/ModelarDB-RS/blob/dev/update-dependencies/server/src/parser.rs#L503) until an alternative solution can be found.

2022-12-07 09:09 UTC, skejserjensen commented on server/src/optimizer/model_simple_aggregates.rs
> + fn size(&self) -> usize {
Fixed.

2022-12-07 09:10 UTC, skejserjensen commented on server/src/parser.rs
> +// changed made in datafusion-sql v15.0.0 to the greatest degree possible. As the private function
Fixed.

2022-12-07 09:11 UTC, skejserjensen commented on server/src/parser.rs
> +// made to try an replace these two functions with calls to Apache Arrow DataFusion's public API
Fixed.

2022-12-07 09:16 UTC, skejserjensen commented on server/src/parser.rs
> +// https://github.com/apache/arrow-datafusion/blob/14.0.0/datafusion/sql/src/planner.rs#L2812
Fixed.

2022-12-07 09:17 UTC, skejserjensen commented on server/src/parser.rs
> +/// Convert SQL simple data type to relational representation of data type
Fixed.

2022-12-07 09:17 UTC, skejserjensen commented on server/src/parser.rs
> +        |SQLDataType::Decimal(exact_number_info) => {
Fixed.

2022-12-07 09:24 UTC, skejserjensen commented on server/src/parser.rs
> +// This function is copied from datafusion-sql v14.0.0/v15.0.0 which was released under Apache-2.0.
Fixed.

2022-12-07 09:25 UTC, skejserjensen commented on server/src/parser.rs
> +// https://github.com/apache/arrow-datafusion/blob/15.0.0/datafusion/sql/src/utils.rs#L506
Fixed.

2022-12-07 09:26 UTC, skejserjensen commented on server/src/parser.rs
> +                "Cannot specify only scale for decimal data type".to_string(),
Fixed.

2022-12-07 15:13 UTC, CGodiksen approved these changes

2022-12-08 10:08 UTC, chrthomsen requested changes

2022-12-08 10:08 UTC, chrthomsen commented on server/src/parser.rs
> +/// v15.0.0]. Both versions of datafusion-sql was released under Apache-2.0.
Apache License 2.0?

+ "and are copyrighted by The Apache Software Foundation" ?

2022-12-08 14:36 UTC, skejserjensen commented on server/src/parser.rs
> +/// v15.0.0]. Both versions of datafusion-sql was released under Apache-2.0.
Fixed.

2022-12-08 16:58 UTC, chrthomsen approved these changes

2022-12-08 19:17 UTC, merged